name: CI/CD AWS Terraform & Docker

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Tag Docker Image
      working-directory: ./docker
      run: |
       docker build -t ${{ vars.IMAGE_NAME }}/custom-image:latest .

    - name: Push Docker Image
      run: |
       docker push ${{ vars.IMAGE_NAME }}/custom-image:latest


    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -var="allowed_ip=${{ vars.ALLOWED_IP }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve -var="allowed_ip=${{ vars.ALLOWED_IP }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
